//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cart
{
    public int CartID { get; set; }
    public string UserID { get; set; }
    public string ItemName { get; set; }
    public int Qty { get; set; }
    public int Price { get; set; }

    public virtual Member Member { get; set; }
}

public partial class Member
{
    public Member()
    {
        this.Carts = new HashSet<Cart>();
    }

    public string UserID { get; set; }
    public string Password { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }

    public virtual ICollection<Cart> Carts { get; set; }
}

public partial class usp_SelectMemberByUserID_Result
{
    public string UserID { get; set; }
    public string Password { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
}
